version: '3'

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/src

    front:
        build: ./docker/php
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9003"
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-"serverName=localhost"}
        volumes:
            - ./src:/var/www/src

    mariadb:
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
        volumes:
            - mariadb:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    mariadb:
        name: ${DB_VOLUME_NAME:-"db-mariadb"}
